### ISSUE TITLE
Class '\Rancher\Model\Base64Model' not found

### ISSUE THREAD

**Issue by nevets963** [freightlive/rancher-php-client#1]
Hi,

We've started to use this library with a project and so far it's working really nicely. We however ran into an issue where there is a modal missing 'Base64Model'. Do you know if this programmatically generated somewhere or if we can generate this somehow?

Thanks!
Steve

**Comment by freightlive** [comment]
Hi Steve, sorry for the late reply; I've added an exception for Base64 types, they should be regarded as strings from now on.

**Comment by nevets963** [comment]
No worries at all. Awesome! Thanks!
